package cn.huibao.ui.view;

import javax.swing.*;
import java.awt.*;

/**
 * Created with IntelliJ IDEA
 * Created By yy
 * Date: 2018-10-09
 * Time: 12:56
 * DES:
 */
public class MainFrame extends JFrame {

    private static final int HEIGHT = 460;
    private static final int WIDTH = 1000;

    private JPanel mainPanel;
    private JLabel msg;
    private JTextField zhouCi;
    private JTextField txtBeginDate;
    private JTextField txtEndDate;
    private JTextField txtFengZhiShiDuanZhuanZhi;
    private JTextField txtFengZhiZhuanZhi;
    private JTextField txtYongDuShiChang;
    private JTextField txtZaoWanGaoFengZhiShu;
    private JTextField txtQuanLuWang;
    private JTextField txtChuGao;
    private JButton btnChangConfig;
    private JButton btnExecute;
    private JTextField txtOut;

    public MainFrame() {
        setTitle("文件整合");

        // 设置大小
        setSize(WIDTH, HEIGHT);
        setContentPane(mainPanel);
        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // 设置窗体居中
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension myFrame = getSize();
        int w = (screen.width - myFrame.width) / 2;
        int h = (screen.height - myFrame.height) / 2;
        setLocation(w, h);
    }

    public JTextField getZhouCi() {
        return zhouCi;
    }

    public void setZhouCi(JTextField zhouCi) {
        this.zhouCi = zhouCi;
    }

    public JTextField getTxtBeginDate() {
        return txtBeginDate;
    }

    public void setTxtBeginDate(JTextField txtBeginDate) {
        this.txtBeginDate = txtBeginDate;
    }

    public JTextField getTxtEndDate() {
        return txtEndDate;
    }

    public void setTxtEndDate(JTextField txtEndDate) {
        this.txtEndDate = txtEndDate;
    }

    public JLabel getMsg() {
        return msg;
    }

    public void setMsg(JLabel msg) {
        this.msg = msg;
    }

    public JTextField getTxtFengZhiShiDuanZhuanZhi() {
        return txtFengZhiShiDuanZhuanZhi;
    }

    public void setTxtFengZhiShiDuanZhuanZhi(JTextField txtFengZhiShiDuanZhuanZhi) {
        this.txtFengZhiShiDuanZhuanZhi = txtFengZhiShiDuanZhuanZhi;
    }

    public JTextField getTxtFengZhiZhuanZhi() {
        return txtFengZhiZhuanZhi;
    }

    public void setTxtFengZhiZhuanZhi(JTextField txtFengZhiZhuanZhi) {
        this.txtFengZhiZhuanZhi = txtFengZhiZhuanZhi;
    }

    public JTextField getTxtYongDuShiChang() {
        return txtYongDuShiChang;
    }

    public void setTxtYongDuShiChang(JTextField txtYongDuShiChang) {
        this.txtYongDuShiChang = txtYongDuShiChang;
    }

    public JTextField getTxtZaoWanGaoFengZhiShu() {
        return txtZaoWanGaoFengZhiShu;
    }

    public void setTxtZaoWanGaoFengZhiShu(JTextField txtZaoWanGaoFengZhiShu) {
        this.txtZaoWanGaoFengZhiShu = txtZaoWanGaoFengZhiShu;
    }

    public JTextField getTxtQuanLuWang() {
        return txtQuanLuWang;
    }

    public void setTxtQuanLuWang(JTextField txtQuanLuWang) {
        this.txtQuanLuWang = txtQuanLuWang;
    }

    public JTextField getTxtChuGao() {
        return txtChuGao;
    }

    public void setTxtChuGao(JTextField txtChuGao) {
        this.txtChuGao = txtChuGao;
    }

    public JButton getBtnChangConfig() {
        return btnChangConfig;
    }

    public void setBtnChangConfig(JButton btnChangConfig) {
        this.btnChangConfig = btnChangConfig;
    }

    public JButton getBtnExecute() {
        return btnExecute;
    }

    public void setBtnExecute(JButton btnExecute) {
        this.btnExecute = btnExecute;
    }

    public JTextField getTxtOut() {
        return txtOut;
    }

    public void setTxtOut(JTextField txtOut) {
        this.txtOut = txtOut;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(10, 6, new Insets(0, 0, 0, 0), -1, -1));
        msg = new JLabel();
        msg.setText("");
        mainPanel.add(msg, new com.intellij.uiDesigner.core.GridConstraints(9, 0, 1, 6, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(60, 60), null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("请输入周次：");
        mainPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zhouCi = new JTextField();
        mainPanel.add(zhouCi, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("请输入开始时间：");
        mainPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtBeginDate = new JTextField();
        mainPanel.add(txtBeginDate, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("请输入结束时间：");
        mainPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(0, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtEndDate = new JTextField();
        mainPanel.add(txtEndDate, new com.intellij.uiDesigner.core.GridConstraints(0, 5, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("峰值时段转置表 - 位置：");
        mainPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtFengZhiShiDuanZhuanZhi = new JTextField();
        mainPanel.add(txtFengZhiShiDuanZhuanZhi, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("峰值转置表 - 位置：");
        mainPanel.add(label5, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtFengZhiZhuanZhi = new JTextField();
        mainPanel.add(txtFengZhiZhuanZhi, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("拥堵时长 - 位置：");
        mainPanel.add(label6, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("早晚高峰指数 - 位置：");
        mainPanel.add(label7, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtYongDuShiChang = new JTextField();
        mainPanel.add(txtYongDuShiChang, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtZaoWanGaoFengZhiShu = new JTextField();
        mainPanel.add(txtZaoWanGaoFengZhiShu, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("全路网高峰指数_峰值_峰值时段 - 位置：");
        mainPanel.add(label8, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtQuanLuWang = new JTextField();
        mainPanel.add(txtQuanLuWang, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label9 = new JLabel();
        label9.setText("周全路网指数预测-初稿 - 位置：");
        mainPanel.add(label9, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtChuGao = new JTextField();
        mainPanel.add(txtChuGao, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label10 = new JLabel();
        label10.setForeground(new Color(-4509140));
        label10.setText("初稿位置：");
        mainPanel.add(label10, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnChangConfig = new JButton();
        btnChangConfig.setText("修改文件位置");
        mainPanel.add(btnChangConfig, new com.intellij.uiDesigner.core.GridConstraints(8, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnExecute = new JButton();
        btnExecute.setText("生成初稿");
        mainPanel.add(btnExecute, new com.intellij.uiDesigner.core.GridConstraints(8, 5, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtOut = new JTextField();
        mainPanel.add(txtOut, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
